hidden_dim: 1360
learning_rate: 0.001
num_epochs: 20
batch_size: 64
filedir: "/scratch/users/samutiti/U54/paired_embeddings_test_small"
shuffle: True
output_dir: 'small_test_march_11'
temperature: 0.07